name: .NET Build
on:
  push:
    branches: [release]
  pull_request:
    branches: [release]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: "recursive"
      - name: Install .NET Core 7
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Build Release
        run: dotnet build -c Release -o dist/release
      - name: Upload Release
        uses: actions/upload-artifact@v3
        with:
          name: cibuild-Release
          path: dist/release
